appleajax/grace-shopper

- server/db/models/index.js
- server/db/models/shoe.js
Finished model for shoe.
---
Have not written tests yet just pushing model for shoe.
> finished issue #4

- server/db/models/user.js
Resolved issue #5 to update the Users model with relevant information
> Updated Users model to include name, address, and cart

- script/seed.js
- server/api/users.js
We're looking for 5 shoes in each category to seed in our database.
---
Finished seeding 5 types of heels #11
> Seed shoe#11

- server/api/users.js
This request is to define the route for single user. issue #6
---
issue #6
> added route for single user

- script/seed.js
---
Added seed data from boots, flip flops. Also required in Shoe model from the db models. Changed the seed success message.
> more shoe seed data

- server/db/models/shoe.js
- server/db/models/user.js
> Updated User and Shoe model #14, #15

- server/api/shoes.js
> shoe routes added

- script/seed.js
Was able to seed sneaker dummy data, the user should see the product in their all products view
---
_issue #19 completed_
> Database seed sneaker#19

- client/store/shoe.js
> redux: added reducer for shoes

- client/app.js
- client/components/errorpage.js
- client/components/index.js
- client/routes.js
Functional front end routing and component name change. 
---
_#30_
> Component frontend errorpage#30

- client/app.js
- client/components/errorpage.js
- client/routes.js
Bare bones error page component (styling comes later) and route/component used in front-end route
Please create tests!
---
_#30 issue completed_
> Component errorpage#30

- package-lock.json
- server/api/index.js
- server/api/orders.js
- server/api/users.js
---
Added two routes in orders- // An admin route for getting all orders and one route for getting singleOrder, including order items. 
One route in users- // a route for getting all orders by a specific customer by customerId
> three new routes in orders and users

- client/components/all-products.js
- script/seed.js
*fixed broken images in the database
*fixed image sizing issue from imageUrl
images working
---
_#39 fixed broken links_
> Fixed  broken links in database / all shoes view size #39

- client/routes.js
Added 404 error page for logging in.
---
> fixed 404 error when you log in

- client/components/errorpage.js
Error page image added
detail added to error page
---
_#30_
> added image to error page

- README.md
- client/components/errorpage.js
README.md now reflects relevant information to our app
> Readme changes#46

- client/components/homepage.js
- client/components/shoes.js
- public/style.css
> css-styling

- client/components/user-home.spec.js
- server/api/cart.js
- server/api/index.js
- server/db/models/cart.js
- server/db/models/cartItem.js
- server/db/models/index.js
> defined cart and cartItems model and routes

- boilermakerREADME.md
Adding a boilermaker readme reference doc.
---
_#46_
> boilermaker readme added

- client/components/index.js
- client/components/shoe.js
- client/routes.js
---
Added link to single product view mounted on "all shoes"
> Adding single view route#49

- script/seed.js
We needed seed data for carts and cartitems!
---
_#54_
> Database cart seed#54

- client/components/auth-form.js
- public/style.css
---
Finished Login/SignUp layout
> style: completed the css for the login/signup components

- package-lock.json
- server/api/index.js
- server/api/oauth.js
- server/index.js
> feat: able to log in with google

- client/components/shoe.js
- client/store/shoe.js
---
I commented out and put some things at the bottom to restore the site's functionality, but there is code in the component file and the reducer that should be able to work once you have the routes.
> feat: add functionality to single shoe cart component

- README.md
Gender neutral wording in README.md
---
_#46_
> chore: update gender wording in readme

- client/components/shoe.js
- client/components/shoes.js
- client/store/index.js
- client/store/order.js
- public/style.css
- server/api/orders.js
- server/db/models/shoe.js
Adding an item to user's cart
---
_#58_
> Single view#58

- boilermakerREADME.md
- server/api/test/orders.spec.js
- server/api/test/shoes.spec.js
- server/api/test/users.spec.js
- server/db/db.js
- server/db/models/test/order.spec.js
- server/db/models/test/user.spec.js
---
I edited the tests that weren't working and added a few. Theres a ~spooky~ red message at the top about an unfulfilled promise (Unhandled rejection Error: ConnectionManager.getConnection was called after the connection manager was closed!). I havent been able to get rid of, but this at least is enough for more working tests to be built
> feat: made tests work, added tests

- client/components/cart.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/order.js
- server/api/orders.js
---
-Made some progress on the cart page, importing in the right information to be displayed for logged in users and guests. 
-Fixed get user thunk
-fixed some API routes
- not fully functional yet, but getting there
> made progress on cart page

- client/components/shoes.js
- client/store/order.js
> style: added decimals to prices

- server/api/test/orders.spec.js
- server/api/test/shoes.spec.js
- server/api/test/users.spec.js
- server/db/models/test/order.spec.js
> feat: commented out tests to see if travis works

- server/index.js
> adding google auth page

- server/db/models/test/user.spec.js
> round 2 for commented out test

- client/components/cart.js
- client/components/shoe.js
- client/components/shoes.js
- client/store/order.js
- client/store/user.js
- script/seed.js
- server/api/orders.js
fixed add to cart feature and added remove button
> Feature fixing cart

- README.md
chore: edited README with correct linkedIN for Sharmin
Fixed Sharmin's Linkedin URL
---
_#46_
> chore: edited README with correct linkedIn

- client/components/cart.js
- client/components/shoe.js
- public/style.css
Fixed the single shoe view
formatted single shoe view
---
_#86_
> Single shoe css#86

- client/components/cart.js
- client/components/shoe.js
Chore: change display of money from pennies to dollars.
---
This PR has no styling changes. (No shoe icon, no font/link changes, just money)
#84
> Money conversion#84 (This PR has no styling changes)

- README.md
Updated README.md to reflect real Heroku link.
chore: updated readme to reflect real heroku app
---
_#46_
> chore: updated readme to reflect heroku link

- .travis.yml
- client/store/index.js
- client/store/shoe.spec.js
- package-lock.json
- package.json
- script/seed.js
- server/api/test/orders.spec.js
- server/api/test/shoes.spec.js
- server/api/test/users.spec.js
- server/db/models/test/order.spec.js
- server/db/models/test/user.spec.js
---
Added tests for a few API. We currently have 13 test specs.
> test: added 2 tests for routes

- client/components/cart.js
- client/components/shoe.js
> style: changed the option and price

- client/components/shoe.js
---
fixed so you can add 1 shoe
> fix: option 0 for qty

- client/components/cart.js
---
-Fixed view for cart component, made it a table 
-Added "continue shopping" button and hyperlinks back to items from their name & image
- Cart will show user's name at the top, or just "Cart" If they arent logged in
> Feat cart table

- client/components/cart.js
- client/components/checkout.js
- client/components/shoe.js
- client/store/shoe.spec.js
- server/api/oauth.js
- server/api/orders.js
- server/api/users.js
> fix: deleted extra comments

- client/components/checkout.js
- client/components/success.js
> fix: new success page

- client/components/shoe.js
---
Added breadcrumbs to the top of single shoe page that redirects to the shoe category, all shoes and the homepage
> Feat breadcrumbs

- client/components/shoe.js
> fixed adding to cart bug

- client/components/cart.js
> updated cart view

- client/components/cart.js
- client/components/edit-cart-item.js
- client/store/order.js
- public/style.css
- server/api/orders.js
> working on editing quantity in cart

- server/api/orders.js
> quantity updates for guest cart

- server/api/orders.js
> updating quantity now updates total
